function(print_system_info) # could be macro(print_system_info)
    message("====================== System info ======================")

    if(${WIN32})
    message("Running on Windows")
    elseif(${LINUX})
    message("Running on Linux")
    endif()

    if(${MSVC})
    message("MSVC version: ${MSVC_VERSION}")
    message("MSVC toolset version: ${MSVC_TOOLSET_VERSION}")
    endif()

    message("Using ${CMAKE_CXX_COMPILER_ID} compiler")
    message("Compiler flags: ${CMAKE_CXX_FLAGS}")
    message("Compiler debug flags: ${CMAKE_CXX_FLAGS_DEBUG}")
    message("Compiler release flags: ${CMAKE_CXX_FLAGS_RELEASE}")

    message("CMAKE_SOURCE_DIR: ${CMAKE_SOURCE_DIR}")
    message("CMAKE_BINARY_DIR: ${CMAKE_BINARY_DIR}")
    message("CMAKE_CURRENT_SOURCE_DIR: ${CMAKE_CURRENT_SOURCE_DIR}")
    message("CMAKE_RUNTIME_OUTPUT_DIRECTORY: ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}")

    message("Configuration types: ${CMAKE_CONFIGURATION_TYPES}")
    message("=========================================================")
endfunction() # or endmacro()

function(setup_precompiled_headers TARGET PCH_SOURCE PCH_HEADER SOURCE_FILES)
    if (MSVC)
        get_filename_component(PCH_HEADER_NAME ${PCH_HEADER} NAME)
        target_sources(${TARGET} PRIVATE ${PCH_HEADER} ${PCH_SOURCE})
        set_source_files_properties(${PCH_SOURCE} PROPERTIES COMPILE_FLAGS "/Yc${PCH_HEADER_NAME}")

        foreach(SOURCE_FILE ${SOURCE_FILES})
            if (${SOURCE_FILE} MATCHES "\\.cpp$" AND NOT ${SOURCE_FILE} STREQUAL ${PCH_SOURCE})
                set_source_files_properties(${SOURCE_FILE} PROPERTIES COMPILE_FLAGS "/Yu${PCH_HEADER_NAME}")
            endif()
        endforeach()
        target_compile_options(${TARGET} PRIVATE "/FI${PCH_HEADER_NAME}")
    endif()    
endfunction()

macro(create_ide_folders SOURCE_FILES)
    foreach(SOURCE_FILE ${SOURCE_FILES})
        get_filename_component(SOURCE_PATH ${SOURCE_FILE} PATH)
        string(REPLACE "${PROJECT_SOURCE_DIR}" "" SOURCE_PATH_REL ${SOURCE_PATH})
        string(REPLACE "/" "\\" GROUP_PATH ${SOURCE_PATH_REL})
        source_group("${GROUP_PATH}" FILES ${SOURCE_FILE})
    endforeach()
endmacro()